### ISSUE TITLE
Redis connection parameters 

### ISSUE THREAD

**Issue by dvasilen** [cargomedia/socket-redis#100]
I am not sure how to specify the port, password and the database for Redis.
I can see the `--redis-host` parameter but it is not clear how to specify the rest.
Please advise.

**Comment by kris-lab** [comment]
I am afraid it's not possible at the moment. The `port` number is still hardcoded at https://github.com/cargomedia/socket-redis/blob/master/lib/server.js#L174 and the `auth` options are not considered too.

I would suggest to parse [host](https://github.com/cargomedia/socket-redis/blob/master/lib/server.js#L173) param as [URL](https://nodejs.org/api/url.html#url_url) and extract user/password/port if URI is valid. Alternatively, we should validate and pass full URL to the [redis.createClient()](https://www.npmjs.com/package/redis#rediscreateclient).

As the results we would pass `--socket-host=[redis:]//[[user][:password@]][host][:port][/db-number][?db=db-number[&password=bar[&option=value]]]`

PR with this improvement is very welcome!

 @tomaszdurka @vogdb wdyt?

**Comment by kris-lab** [comment]
Please open the PR if you want this feature.
