### ISSUE TITLE
Is it possible to enable CORS?

### ISSUE THREAD

**Issue by Dayjo** [cargomedia/socket-redis#110]
Hello, having fun playing with WebSockets using this library, but I'm wondering if it's possible to set the `Access-Control-Allow-Origin` header to allow cross-origin access? I'm getting cancelled and failed requests when the info requests hit. 

If you'd like any further information I can provide it.

**Comment by njam** [comment]
Usually SockJS automatically sets `Access-Control-Allow-Origin` based on the `Origin` header it receives (see for example discussion here: https://github.com/sockjs/sockjs-node/issues/217).

If that doesn't work for you I would suggest to put a reverse proxy in front of socket-redis, for example with nginx. Then you can also do SSL-termination there. Here's a config to get you started:
```
upstream backend-socketredis {
    server localhost:8091;
    server localhost:8092;
    ip_hash;
}

server {
  listen       *:443 ssl http2;
  server_name  example.com;

  ssl_certificate      /etc/nginx/ssl/example.com.pem;
  ssl_certificate_key  /etc/nginx/ssl/example.com.key;

  location / {
    proxy_pass http://backend-socketredis;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_read_timeout 60;
    proxy_buffering off;
    add_header 'Access-Control-Allow-Origin' '*';
  }
}
```

**Comment by Dayjo** [comment]
@njam I've not really identified if it is a permanent issue, or just one whilst developing on local dev domains. 

I will likely follow your suggestion anyway as nginx would let me have a little better control of the incoming traffic.
