### ISSUE TITLE
Can't get information from Redis in browser

### ISSUE THREAD

**Issue by ssuperczynski** [cargomedia/socket-redis#56]
@tomaszdurka @kris-lab Is it normal that I can not send message from Redis directly to browser/browsers?

Lets say I have code 

```javascript
<html>
<head>
  <title>wss</title>
	<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/sockjs-client/0.3.4/sockjs.min.js"></script>
	<script src="socket-redis.js"></script>
<script>

  var socketRedis = new SocketRedis('http://127.0.0.1:8090');
      socketRedis.onopen = function() {
		console.log('open');
	    	socketRedis.subscribe('test', null, 'bar', function(event, data) {
		console.log('New event `' + event + '` on channel `channel-name`:', data);
	    });
	socketRedis.publish('test', 'bar', 'test');

	};
</script>
</head>
<body>
<h1>ws test</h1>
</body>
</html>
```

When I open two differnet browsers I am getting correct info:
![screenshot from 2015-06-28 17 47 00](https://cloud.githubusercontent.com/assets/6843074/8397040/dca973bc-1dbd-11e5-8f5e-d0718704d04b.png)

Same when I subscribe in Redis to channel `socket-redis-up`
![screenshot from 2015-06-28 17 51 13](https://cloud.githubusercontent.com/assets/6843074/8397058/a50dab0c-1dbe-11e5-8a7f-7b1e0bb9c00c.png)

But when I'm doing same operation from Redis `publish test test` there is no info in browser console.

**Comment by njam** [comment]
To send a message to a channel from Redis you would publish to `socket-redis-down`.
For example you could do:
```
publish socket-redis-down '{"type":"publish", "data": {"channel":"test", "event":"foo", "data":"hello"}}'
```

See [docu in the readme](https://github.com/cargomedia/socket-redis#messages-which-are-detected-on-redis-pubsub-channel-socket-redis-down).

(it can be a bit confusing - there are two redis *pub/sub channels* used (`socket-redis-down` and `socket-redis-up`), and on top of that there are the *websocket channels* which allow a client to subscribe to messages of a specific *websocket channel*.)

Does that anwer your question?

**Comment by ssuperczynski** [comment]
Thanks @njam it works!
