### ISSUE TITLE
Error publishing

### ISSUE THREAD

**Issue by borisovdmitry** [cargomedia/socket-redis#62]
Hi. When I try to send a message to the channel via the function

> socketRedis.publish('channel-name', {foo: 'bar'});

I receive an error

> Error processing WebSocket data: Missing data:'{"channel":"channel-name","event":{"foo":"bar"}}'

To install this module, use the command (the installation was successful)

> npm install socket-redis

**Comment by njam** [comment]
Oh, docu is wrong :/ Will fix it here: https://github.com/cargomedia/socket-redis/pull/63

The signature on the client side is:
```
	/**
	 * @param {String} channel
	 * @param {String} event
	 * @param {Object} data
	 */
	Client.prototype.publish = function(channel, event, data)
```

So you'll do for example:
```js
socketRedis.publish('channel-name', 'event-name', {foo: 'bar'});
```

Does this work for you?

**Comment by borisovdmitry** [comment]
Yes, thank you)
