### ISSUE TITLE
Add "status secret" to limit access to status endpoint

### ISSUE THREAD

**Issue by njam** [cargomedia/socket-redis#93]
Via https://github.com/cargomedia/puppet-cargomedia/issues/1702

The idea is to introduce a "secret" (some string), which is limiting access to the *status* endpoint.
This will make deployment of the service easier, as we don't need to care about whether the status *port* is publicly accessible or not.

I suggest we expect the secret to be sent with an HTTP header when requesting the status.
@vogdb wdyt? could you implement it? how does it relate to your other PRs?
@tomaszdurka any thoughts?

**Comment by vogdb** [comment]
Shouldn't be hard, I think.

**Comment by vogdb** [comment]
will be handled in #97

**Comment by vogdb** [comment]
@njam it's ready
